/* Generated by Cython 0.29.23 */

#ifndef __PYX_HAVE__CySimulator
#define __PYX_HAVE__CySimulator

#include "Python.h"

#ifndef __PYX_HAVE_API__CySimulator

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C float G;

#endif /* !__PYX_HAVE_API__CySimulator */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initCySimulator(void);
#else
PyMODINIT_FUNC PyInit_CySimulator(void);
#endif

#endif /* !__PYX_HAVE__CySimulator */
